- name: ensure EPEL release installed and updated
  yum:
    name: epel-release
    state: latest
- name: ensure pip is installed at latest version
  yum:
    name: python-pip
    state: latest
- name: ensure nfs-utils is installed at latest version
  yum:
    name: nfs-utils
    state: latest
- name: ensure libnfsidmap is installed at latest version
  yum:
    name: libnfsidmap
    state: latest
- name: ensure rpcbind is installed at latest version
  yum:
    name: rpcbind
    state: latest
- name: ensure all installed packages are at latest versions
  yum:
    name: '*'
    state: latest
- name: ensure nfs-server is up and running
  service:
    name: nfs-server
    state: started
- name: ensure rpcbind is up and running
  service:
    name: rpcbind
    state: started
- name: Set share file path here
  set_fact: nfs_share_path=/var/nfs

- name: Create main NFS share location
  file: path={{ nfs_share_path }} state=directory owner=nobody group=nobody mode=0755

# Define file path
- name: Set export file path here
  set_fact: nfs_epxports_path=/etc/exports 

#create a blank file
- name: Create a new file
  file: path="{{ nfs_epxports_path }}" state=touch

- stat: path="{{ nfs_epxports_path }}"
  register: file_path

# Write file content in file_content variable
- set_fact: file_content="{{ nfs_share_path }} 192.168.0.0/24(rw,sync)"

# If file exist then copy content in remote file.
- copy: content="{{ file_content }}" dest="{{ nfs_epxports_path }}"
  when: file_path.stat.exists == true

- name: run the export file and restart nfs-server
  command: exportfs -ra
  notify: nfs-restart
