- name: ensure EPEL release installed and updated
  yum:
    name: epel-release
    state: latest
- name: ensure pip is installed at latest version
  yum:
    name: python-pip
    state: latest
- name: ensure nfs-utils is installed at latest version
  yum:
    name: nfs-utils
    state: latest
- name: ensure libnfsidmap is installed at latest version
  yum:
    name: libnfsidmap
    state: latest
- name: ensure rpcbind is installed at latest version
  yum:
    name: rpcbind
    state: latest
- name: ensure all installed packages are at latest versions
  yum:
    name: '*'
    state: latest
